# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cbind_cpp <- function(x, y) {
    .Call('bayesianrvfl_cbind_cpp', PACKAGE = 'bayesianrvfl', x, y)
}

